CREATE TABLE REF_DEVICE 
(
  ID              NUMBER(10, 0) NOT NULL,
  SERIAL_NUMBER   NVARCHAR2(50) NOT NULL,
  NAME            NVARCHAR2(50),
  DESCRIPTION     NVARCHAR2(150),
  CONSTRAINT PK_REF_DEVICE_ID PRIMARY KEY (ID),
  CONSTRAINT KEY_REF_DEVICE_SERIAL_NUMBER UNIQUE (SERIAL_NUMBER)
);

INSERT ALL
    INTO REF_DEVICE (ID, SERIAL_NUMBER) VALUES (1, 111)
    INTO REF_DEVICE (ID, SERIAL_NUMBER) VALUES (2, 222)
    INTO REF_DEVICE (ID, SERIAL_NUMBER) VALUES (3, 333)
    INTO REF_DEVICE (ID, SERIAL_NUMBER) VALUES (4, 444)
    INTO REF_DEVICE (ID, SERIAL_NUMBER) VALUES (5, 555)
SELECT 1 FROM DUAL;

CREATE TABLE DEVICE_USAGE (
  ID            NUMBER(10, 0) NOT NULL,
  REF_DEVICE_ID NUMBER(10, 0) NOT NULL,
  BRIGADE_CODE  NUMBER(10, 0) NOT NULL,
  USAGE_DATE    DATE          NOT NULL,
  CONSTRAINT PK_DEVICE_USAGE_ID PRIMARY KEY (ID),
  CONSTRAINT FK_DEVICE_USAGE_REF_DEVICE_ID FOREIGN KEY (REF_DEVICE_ID) REFERENCES REF_DEVICE (ID),
  CONSTRAINT KEY_DEVICE_USAGE UNIQUE (BRIGADE_CODE, USAGE_DATE, REF_DEVICE_ID)
);

INSERT ALL
    INTO DEVICE_USAGE (ID, REF_DEVICE_ID, BRIGADE_CODE, USAGE_DATE) VALUES (1, 1, 1234, TO_DATE('01.06.2020', 'dd.mm.yyyy'))
    INTO DEVICE_USAGE (ID, REF_DEVICE_ID, BRIGADE_CODE, USAGE_DATE) VALUES (2, 2, 1234, TO_DATE('02.06.2020', 'dd.mm.yyyy'))
    INTO DEVICE_USAGE (ID, REF_DEVICE_ID, BRIGADE_CODE, USAGE_DATE) VALUES (3, 3, 5678, TO_DATE('01.06.2020', 'dd.mm.yyyy'))
SELECT 1 FROM DUAL;

CREATE TABLE LISTCODE (
  ID                   NUMBER(10, 0) NOT NULL,
  DEVICE_SERIAL_NUMBER NVARCHAR2(50) NOT NULL,
  CHANNEL_ID           NUMBER(10, 0) NOT NULL,
  PDT                  DATE          NOT NULL,
  BRIGADE_CODE         NUMBER(10, 0) NOT NULL,
  WORK_CODE            NUMBER(10, 0) NOT NULL,
  CONSTRAINT PK_LISTCODE_ID PRIMARY KEY (ID),
  CONSTRAINT KEY_LISTCODE UNIQUE (DEVICE_SERIAL_NUMBER, CHANNEL_ID, PDT, BRIGADE_CODE, WORK_CODE)
);

INSERT ALL
    INTO LISTCODE (ID, DEVICE_SERIAL_NUMBER, BRIGADE_CODE, PDT, CHANNEL_ID, WORK_CODE) VALUES (1, 111, 1234, TO_DATE('01.06.2020', 'dd.mm.yyyy'), 1, 1)
    INTO LISTCODE (ID, DEVICE_SERIAL_NUMBER, BRIGADE_CODE, PDT, CHANNEL_ID, WORK_CODE) VALUES (2, 222, 1234, TO_DATE('02.06.2020', 'dd.mm.yyyy'), 1, 1)
    INTO LISTCODE (ID, DEVICE_SERIAL_NUMBER, BRIGADE_CODE, PDT, CHANNEL_ID, WORK_CODE) VALUES (3, 333, 5678, TO_DATE('01.06.2020', 'dd.mm.yyyy'), 1, 1)
    INTO LISTCODE (ID, DEVICE_SERIAL_NUMBER, BRIGADE_CODE, PDT, CHANNEL_ID, WORK_CODE) VALUES (4, 333, 1234, TO_DATE('30.06.2020', 'dd.mm.yyyy'), 1, 1)
    INTO LISTCODE (ID, DEVICE_SERIAL_NUMBER, BRIGADE_CODE, PDT, CHANNEL_ID, WORK_CODE) VALUES (5, 444, 9012, TO_DATE('01.06.2020', 'dd.mm.yyyy'), 1, 1)
    INTO LISTCODE (ID, DEVICE_SERIAL_NUMBER, BRIGADE_CODE, PDT, CHANNEL_ID, WORK_CODE) VALUES (6, 555, 5678, TO_DATE('31.05.2020', 'dd.mm.yyyy'), 1, 1)
SELECT 1 FROM DUAL;



SELECT LIST.DEVICE_SERIAL_NUMBER, LIST.BRIGADE_CODE, LIST.PDT
FROM LISTCODE LIST
JOIN REF_DEVICE DEV 
    ON LIST.DEVICE_SERIAL_NUMBER = DEV.SERIAL_NUMBER
LEFT JOIN DEVICE_USAGE DU 
    ON LIST.BRIGADE_CODE = DU.BRIGADE_CODE
        AND LIST.PDT = DU.USAGE_DATE
        AND LIST.DEVICE_SERIAL_NUMBER = DEV.SERIAL_NUMBER
WHERE (LIST.PDT BETWEEN TO_DATE('01.06.2020', 'dd.mm.yyyy') 
    AND TO_DATE('30.06.2020', 'dd.mm.yyyy'))
    AND DU.USAGE_DATE IS NULL;